# Generated by Django 5.2 on 2025-05-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanworkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_imagea/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='service_imagea/')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('duraction', models.FloatField(blank=True, null=True)),
                ('star', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galery_images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cleanworkapp.service')),
            ],
            options={
                'verbose_name': 'Photo Gallery',
                'verbose_name_plural': 'Photo Galleries',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Servicetag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('services', models.ManyToManyField(related_name='tags', to='cleanworkapp.service')),
            ],
            options={
                'verbose_name': 'Service Tag',
                'ordering': ('-id',),
            },
        ),
    ]
