# Generated by Django 5.2 on 2025-05-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanworkapp', '0002_service_alter_banner_options_gallery_servicetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='companies_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='custom_imagea/')),
                ('title', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icontent', models.TextField()),
                ('image', models.ImageField(upload_to='settings_images/')),
                ('elogo', models.ImageField(upload_to='settings_images/')),
                ('location', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256)),
                ('etitle', models.CharField(max_length=50)),
                ('service_hours', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
